# Generated by Django 3.1.2 on 2021-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('complectation', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('power', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=50)),
                ('top_speed', models.PositiveIntegerField()),
            ],
        ),
    ]
