# Generated by Django 3.1.2 on 2021-10-29 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211029_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('payment', models.PositiveIntegerField()),
                ('percent', models.CharField(max_length=20)),
                ('total', models.PositiveIntegerField()),
                ('remains', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='first_payment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='percent',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
