# Generated by Django 3.1.2 on 2021-10-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211029_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='credit',
            name='car',
        ),
        migrations.AddField(
            model_name='calculator',
            name='credit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.credit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='complectation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.complectation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='complectation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.complectation'),
        ),
    ]
