# Generated by Django 3.1.2 on 2021-10-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211029_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='percent',
        ),
        migrations.AlterField(
            model_name='calculator',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to='cars.credit'),
        ),
    ]
