# Generated by Django 3.1.2 on 2021-11-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20211103_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='complectation',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='complectation',
            new_name='title',
        ),
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.IntegerField(choices=[(1, 'Credit'), (2, 'Leasing')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carmodel'),
        ),
    ]
