# Generated by Django 3.1.2 on 2021-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20211103_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.IntegerField(choices=[('credit', 'Credit'), ('leasing', 'Leasing')]),
        ),
    ]
