# Generated by Django 3.1.2 on 2021-11-06 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20211106_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='month',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
