# Generated by Django 3.1.2 on 2021-11-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_credit_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('credit', 'Credit'), ('leasing', 'Leasing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='cars.car'),
        ),
    ]
