# Generated by Django 3.1.2 on 2021-11-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_credit_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='payment',
            new_name='sum',
        ),
        migrations.AddField(
            model_name='calculator',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
