# Generated by Django 3.1.2 on 2021-11-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20211106_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='remains',
            new_name='remain',
        ),
    ]
